package c.exception;

public class ThrowableSample {

    public static void main(String[] args) {
        ThrowableSample throwableSample = new ThrowableSample();
        throwableSample.throwable();
    }

    public void throwable() {
        int[] intArray = new int[5];
        try {
            intArray = null;
            System.out.println(intArray[5]);
        }
        catch (Throwable t) {
            System.out.println(t.getMessage());
            System.out.println(t.toString());
            t.printStackTrace();
        }
    }
}